export const plans = {
  FREE: {
    name: "Free",
    price: "₹0",
    basePrice: 0,
    description: "Perfect for trying out basic features.",
    features: [
      "Up to 3 offers/month",
      "10 Candidate Ghosting Alerts",
      "10 Candidate Search",
      "Basic Offer Punch",
      "Basic Analytics",
      "Email Support",
    ],
  },
  STARTER: {
    name: "Starter",
    price: "₹799",
    basePrice: 799,
    yearlyPrice: "₹7999",
    yearlyBasePrice: 7999,
    description: "Perfect for small teams making up to 10 offers per month.",
    features: [
      "Up to 10 offers/month",
      "30 Candidate Ghosting Alerts",
      "30 Candidate Search",
      "Unlimited Offer Punch",
      "Basic Analytics",
      "Email Support",
    ],
  },
  GROWTH: {
    name: "Growth",
    price: "₹2499",
    basePrice: 2499,
    yearlyPrice: "₹24999",
    yearlyBasePrice: 24999,
    description: "Ideal for growing teams making up to 50 offers per month.",
    features: [
      "Up to 50 offers/month",
      "200 Candidate Ghosting Alerts",
      "200 Candidate Search",
      "Unlimited Offer Punch",
      "Full Analytics Suite",
      "Priority Support",
    ],
  },
  ENTERPRISE: {
    name: "Enterprise",
    price: "Custom",
    basePrice: 0,
    description: "For large organizations with custom requirements.",
    features: [
      "Unlimited offers",
      "Unlimited Candidate Ghosting Alerts",
      "Unlimited Candidate Search",
      "Unlimited Offer Punch",
      "Dedicated Account Manager",
      "Custom Integrations",
      "SLA & Premium Support",
    ],
  },
};